knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    true
        binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"'
        #binary:     wkhtmltoimage
        options:
            width: 300
            height: 500
    #temporary_folder: '%kernel.cache_dir%\snappy'